language: node_js
cache: npm

addons:
  ssh_known_hosts: tempel.uberspace.de

before_install:
  - echo "//npm.pkg.github.com/:_authToken=${TRAVISCICOM_READ_PACKAGES}" > ~/.npmrc
  - echo "@simonknittel:registry=https://npm.pkg.github.com" > .npmrc

before_script:
  # Use latest commit within master branch of @simonknittel/components
  - wget -O - https://github.com/simonknittel/components/tarball/master | tar xz
  - for file in simonknittel-components-* ; do mv $file simonknittel-components ; done
  - mv simonknittel-components/stencil node_modules/@simonknittel/components
  - cd node_modules/@simonknittel/components
  - npm install
  - npm run build
  - cd ../../../
  - rm -rf simonknittel-components

script:
- npm run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_478fffb56983_key -iv $encrypted_478fffb56983_iv -in id_ed25519.enc -out id_ed25519 -d
- eval "$(ssh-agent -s)"
- chmod 600 id_ed25519
- ssh-add id_ed25519

deploy:
- provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/ $DEPLOYMENT_TARGET
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(nightly|beta|master)$

after_deploy:
  # Notify Sentry of successful deployment
  - curl -sL https://sentry.io/get-cli/ | bash
  - sentry-cli releases new -p $VUE_APP_SENTRY_PROJECT "$VUE_APP_SENTRY_PROJECT@$TRAVIS_BUILD_NUMBER"
  - sentry-cli releases set-commits --auto "$VUE_APP_SENTRY_PROJECT@$TRAVIS_BUILD_NUMBER"
  - sentry-cli releases finalize "$VUE_APP_SENTRY_PROJECT@$TRAVIS_BUILD_NUMBER"
  - sentry-cli releases deploys "$VUE_APP_SENTRY_PROJECT@$TRAVIS_BUILD_NUMBER" new -e $VUE_APP_SENTRY_ENVIRONMENT

notifications:
  webhooks:
    if: branch = nightly
    urls:
      - https://webhooks.datocms.com/3e17ba2f791b63dacca2/deploy-results
