name: build_and_deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'nightly.simonknittel.de'

jobs:

  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.16.0

    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

    - run: npm ci

    - name: Build
      run: |
        export SENTRY_ENVIRONMENT=${{ github.event.inputs.environment }}
        npm run build

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Upload to Cloud Storage
      run: gsutil -m rsync -r -d public gs://${{ github.event.inputs.environment }}

    - name: Invalidate cache
      run: |
        gcloud compute url-maps invalidate-cdn-cache simonknittelde \
          --host ${{ github.event.inputs.environment }} \
          --path "/*"

    - name: Notify Dato CMS (Success)
      if: ${{ success() }}
      run: |
        curl -n -X POST https://webhooks.datocms.com/${{ secrets.DATO_CMS_NIGHTLY_WEBHOOK }}/deploy-results \
          -H 'Content-Type: application/json' \
          -d '{ "status": "success" }'

    - name: Notify Dato CMS (Failure)
      if: ${{ failure() }}
      run: |
        curl -n -X POST https://webhooks.datocms.com/${{ secrets.DATO_CMS_NIGHTLY_WEBHOOK }}/deploy-results \
          -H 'Content-Type: application/json' \
          -d '{ "status": "error" }'
