name: build_and_deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'nightly.simonknittel.de'
      useCache:
        description: 'Use cache'
        required: false
        default: 'yes'

jobs:

  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.16.0

    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

    - name: Cache node_modules
      id: cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json', '.nvmrc') }}

    - name: Clear node_modules
      if: github.event.inputs.useCache == 'no'
      run: rm -rf node_modules

    - run: npm ci
      if: github.event.inputs.useCache == 'no' || steps.cache.outputs.cache-hit == 'false'

    - name: Cache Gatsby
      uses: actions/cache@v2
      with:
        path: |
          .cache
          public
        key: gatsby-${{ github.run_id }}
        restore-keys: |
          gatsby-

    - name: Clear Gatsby cache
      if: github.event.inputs.useCache == 'no'
      run: rm -rf .cache public

    - name: Build
      run: |
        export SENTRY_ENVIRONMENT=${{ github.event.inputs.environment }}
        npm run build

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Gzip files
      run: |
        gzip -r public
        find public -type f -name "*.*" -exec sh -c 'for pathname; do mv -i "$pathname" "${pathname%.*}"; done' sh {} +

    - name: Upload to Cloud Storage
      run: |
        gsutil \
          -m \
          -q \
          -h "Content-Encoding: gzip" \
        rsync \
          -r \
          -d public \
        gs://${{ github.event.inputs.environment }}

    # Source: https://www.gatsbyjs.com/docs/caching/
    - name: Set Cache-Control headers
      run: |
        gsutil -m -q setmeta -h "Cache-Control: public, max-age=31536000, immutable" \
          gs://nightly.simonknittel.de/static/** \
          gs://nightly.simonknittel.de/icons/** \
          gs://nightly.simonknittel.de/favicon** \
          gs://nightly.simonknittel.de/**.css \
          gs://nightly.simonknittel.de/**.js || :

        gsutil -m -q setmeta -h "Cache-Control: public, max-age=0, must-revalidate" \
          gs://nightly.simonknittel.de/**.html \
          gs://nightly.simonknittel.de/page-data/** \
          gs://nightly.simonknittel.de/robots.txt \
          gs://nightly.simonknittel.de/sitemap.xml \
          gs://nightly.simonknittel.de/manifest.webmanifest \
          gs://nightly.simonknittel.de/rss.xml || :

    # Source: https://cloud.google.com/cdn/docs/invalidating-cached-content
    - name: Invalidate CDN cache
      run: |
        gcloud compute url-maps invalidate-cdn-cache simonknittelde \
          --host ${{ github.event.inputs.environment }} \
          --path "/*"

    - name: Notify Dato CMS (Success)
      if: ${{ success() }}
      run: |
        curl -n -X POST https://webhooks.datocms.com/${{ secrets.DATO_CMS_NIGHTLY_WEBHOOK }}/deploy-results \
          -H 'Content-Type: application/json' \
          -d '{ "status": "success" }'

    - name: Notify Dato CMS (Failure)
      if: ${{ failure() }}
      run: |
        curl -n -X POST https://webhooks.datocms.com/${{ secrets.DATO_CMS_NIGHTLY_WEBHOOK }}/deploy-results \
          -H 'Content-Type: application/json' \
          -d '{ "status": "error" }'
