name: build

on:
  push:

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.16.0

    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

    # Source: https://github.com/actions/cache/blob/main/examples.md#node---npm
    # - name: Cache
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.npm
    #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-node-

    # Source: https://github.com/actions/cache/blob/main/examples.md#node---npm
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/.nvmrc') }}

    - run: npm ci
      if: steps.cache.outputs.cache-hit != 'true'

    - run: npm run build
