name: owasp_zap

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:
  
jobs:
  owasp_zap:
    runs-on: ubuntu-20.04
    steps:
      - name: Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'https://simonknittel.de/'
